---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "The day the application died"
      solveButton: false
    # - name: module-02  ## Insights not working - need to fix
    #   label: "All your vulnerabilities are belong to us"
    #   solveButton: false
    - name: module-02
      label: "Oh no whats next, the network ?"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: ">_ S.E.A.N"
    url: /wetty_sean
  - name: Webapp
    url: https://podman-host-${guid}.${domain}/index.html
    external: true
  - name: ServiceNow
    url: https://ansible.service-now.com
    external: true
  # - name: Red Hat Insights
  #   url: https://console.redhat.com
  #   external: true
